title: Boolean
site.name: Boolean Inc.
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

gems:
  - jekyll-seo-tag


exclude:
  - Gemfile
  - Gemfile.lock

